epoch: 200
batch_size: 4
num_worker: 8
classes: 11
lr: 0.0001
decoder: FPN # Unet, UnetPlusPlus, DeepLabV3, DeepLabV3Plus
encoder: timm-efficientnet-b4 # Segmentation Model 보는게 더 빠름
encoder_weights: imagenet # imagenet / advprop / noisy-student
criterion: focal # dice / CE / focal / softCE